apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongospace
  labels:
    app: mongodb-service
spec:
  ports:
  - port: 27017
    protocol: TCP
  # 指定Service的Selector，來代理Pod的Label
  selector:
    app: mongodb-pod